@baseUrl = http://localhost
@token = your-token-here

@port = 8080

### welcome
GET {{baseUrl}}:{{port}}/welcome HTTP/1.1

### form_post
POST {{baseUrl}}:{{port}}/form_post
Content-Type: application/x-www-form-urlencoded
User-Agent: restclient

message=zjs
nick=zjs


### json
POST {{baseUrl}}:{{port}}/form_post HTTP/1.1
Content-Type: application/json
User-Agent: restclient

{
    "name" : "zjs",
    "age" : 18
}

### upload
POST {{baseUrl}}:{{port}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gWX
User-Agent: restclient

------WebKitFormBoundary7MA4YWxkTrZu0gWX
Content-Disposition: form-data; name="file"; filename="IMG_1215.jpg"
Content-Type: image/jpeg


< /Users/zhongjiasheng/Documents/IMG_1215.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gWX--

