@baseUrl = http://localhost
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpc3MiOiJnby1zdHVkeS1ibG9nIiwiZXhwIjoxNzU5Mzg5MzY2LCJuYmYiOjE3NTkzMDI5NjYsImlhdCI6MTc1OTMwMjk2NiwianRpIjoiNTc5OGM5MTAtMGU1MC00OGVjLWExZmMtZTdkZGM2ZjcwMzY1In0.sggxF3FED6dxcp1lc0y6rG9XH2eQstwovVvmiFefuF8

@port = 8080

### create
POST {{baseUrl}}:{{port}}/api/auth/posts HTTP/1.1
Authorization: Bearer {{token}}
User-Agent: restclient

{
    "title" : "title4",
    "content" : "content4"
}


### get_post
GET {{baseUrl}}:{{port}}/api/auth/posts/1 HTTP/1.1
Authorization: Bearer {{token}}

### get_all_posts
GET {{baseUrl}}:{{port}}/api/auth/posts HTTP/1.1
Authorization: Bearer {{token}}

### update_post
PUT {{baseUrl}}:{{port}}/api/auth/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "id" : 1,
    "title" : "title1x"
}
